### ISSUE TITLE
predict throws error with checkTerms when new dataframe used as input

### ISSUE THREAD

**Issue by MelanieDou** [glmmTMB/glmmTMB#383]
I have been trying to use `predict ` to predict new values for a beta mixed effect regression model. When using the same database than the one used to fit the model, the function work fine. When I specify in a new data frame the values I want to use (fixed and random effects), I get the following error: 
`Error in checkTerms(data.tmb1$terms, data.tmb0$terms) : 
  identical(names(t1), names(t0)) is not TRUE`
The code used is the following: 
```
newdatat <-data.frame(seq(min(database[,"fixedeffects1"),max(database[,"fixedeffects1"]),length.out=1000),
sample(database$randomeffect1,1000),
sample(database$randomeffect2,1000),
sample(database$randomeffect3,1000),
sample(database$randomeffect4,1000),
sample(database$randomeffect5,1000))
colnames(newdatat) <- c(fixedeffects1,"randomeffect1","randomeffect2",
                        "randomeffect3","randomeffect4","randomeffect5")
predstest <- predict(B_per_fe[[f]],allow.new.levels = T,newdata = newdatat,type = "response")
```
And I am using the following structure for the model: 
`fraction ~ fixedeffecst1 + (1 | randomeffect2/randomeffect1) + 
    (1 | randomeffect5) + (1 | randomeffect4/randomeffect3)`

Is it something about the way I structure the dataset? 
Or is it something else?

**Comment by mebrooks** [comment]
Is it possible to make a reproducible example by simulating data?

**Comment by mebrooks** [comment]
My initial guess is that your `newdata` is missing a column that the model needs (something in one of the formulas), but without seeing the code, it's hard to tell for sure.

**Comment by koenvanbenthem** [comment]
Quick observation:
in your data frame, the first term is called 
`fixedeffects1`
but in your model structure it is called:
`fixedeffecst1`
(not the typo)

Furthremore, when specifying the column names of the new data frame, the first term is not in quotation marks.

Maybe this helps?

**Comment by MelanieDou** [comment]
Ok... I tried to generate a reproducible example with new data and did not get any issue. So I guess something is missing when I generate the data. Will look at my code more carefully. Thank you both very much for your quick replies!

**Comment by koenvanbenthem** [comment]
Have you tried correcting the typo(s) (https://github.com/glmmTMB/glmmTMB/issues/383#issuecomment-418333069)? 

Please let us know whether the problem solved now, so we can close this issue.

**Comment by MelanieDou** [comment]
I have tried but did not solve it yet, but please go ahead and close this issue. Thank you

**Comment by MelanieDou** [comment]
Sorry to reopen this but I am still struggling. Could it be the order of the columns when I create the newdataframe? I have the following reproducible code: 
```
database_test <- data.frame(fraction=rbeta(1000,15,2),
                       fixedeffect1=rnorm(1000,10,1.7),
                       fixedeffect2=rnorm(1000,500,13.6),
                       randomeffect1=sample(c("A","B","C","D","E"),10,replace=T),
                       randomeffect2=sample(c("Am1","Re3","Dr4"),10,replace=T),
                       randomeffect3=sample(seq(1,14), 10,replace=T),
                       randomeffect4=sample(c("c1","c2","c3","c4","c5","c6","c7","c8","c9","c10"),10,replace=T),
                       randomeffect5=sample(c("Y","X","Z"),10,replace=T),
                       randomeffect6=sample(seq(1,100),10,replace=T))
form.prov.mixed_test <- formula(paste("fraction ~ fixedeffect1+(1|randomeffect2/randomeffect1)+(1|randomeffect5)+(1|randomeffect4/randomeffect3)"))

Betamixedmodel <- glmmTMB(form.prov.mixed_test,database_test, family=beta_family(link="logit"),verbose = F,REML=F)

newdatat <- data.frame(seq(min(database_test[,"fixedeffect1"]),max(database_test[,"fixedeffect1"]),length.out=400),
                       sample(database_test$randomeffect1,400,replace=T),
                       sample(database_test$randomeffect2,400,replace=T),
                       sample(database_test$randomeffect3,400,replace=T),
                       sample(database_test$randomeffect4,400,replace=T),
                       sample(database_test$randomeffect5,400,replace=T))
colnames(newdatat) <- c("fixedeffect1","randomeffect1","randomeffect2",
                        "randomeffect3","randomeffect4","randomeffect5") ## works fine
colnames(newdatat) <- c("fixedeffect1","randomeffect2","randomeffect1",
                        "randomeffect3","randomeffect4","randomeffect5") ## throws the checkTerms error

predstest <- predict(Betamixedmodel,allow.new.levels = T,newdata = newdatat,type = "response")
```

Depending on how I assign the column names, predstest works or throws the checkTerms error I was talking about previously. Any ideas why?

**Comment by MelanieDou** [comment]
No, I think I found it: the reason is that when I change the order of the colnames, I submit new random effect combinations that were not used in the model fitting. I am a bit surprised that it does not work to have new levels. I thought this is why the argument: allow.new.levels = T was for. What am I misunderstanding?

**Comment by koenvanbenthem** [comment]
I just had a quick look, but I think it's important to realize that when you change the column names, you are not actually also shifting the accompanying data (columns). When actually shifting the full columns, predict seems to work fine:
```
colnames(newdatat) <- c("fixedeffect1","randomeffect1","randomeffect2",
                        "randomeffect3","randomeffect4","randomeffect5") ## works fine
newdatat2 <- newdatat[,c(1,3,2,4,5,6)]

predstest <- predict(Betamixedmodel,allow.new.levels = T,newdata = newdatat,type = "response")
predstest2 <- predict(Betamixedmodel,allow.new.levels = T,newdata = newdatat2,type = "response")
identical(predstest,predstest2)
```
returns `TRUE` on my machine. In principle, `allow.new.levels = T` should allow for the addition of new levels.  This is funny behaviour and I'm currently not sure why this is happening.

**Comment by strengejacke** [comment]
Is `allow.new.levels` fully implemented yet? I thought it wasn't, as well as `re.form` is not implemented yet.

**Comment by MelanieDou** [comment]
Is it not? re.form gives out that it is not implemented but since I did not get anything from allow.new.levels I assumed it was. I would need such a feature to carry out a cross-validation of the models I fit. Would you have any suggestion on how I should best implement such a predict function that works even with new levels for the random effects? Would it be justifiable to only use the fixed effect parts and see how this model performs when predicting new data?

**Comment by strengejacke** [comment]
You're right. But `allow.new.levels` does not alter the results, it just throws a warning when set to `FALSE` and new levels are present. So, new levels are always possible. I have never used this arguments, also not for other models, so I'm not sure if this is the typical behaviour.

**Comment by MelanieDou** [comment]
I see.. Thank you. Does anybody else have a suggestion on how I should implement the predict function in order for it to work on my data?

**Comment by MelanieDou** [comment]
As far as I came: the error comes from the `assertIdenticalModels ` function in the `predict` function because the order of the terms is not the same when `stopifnot(identical(names(t1), names(t0)))` is called. There must be something in the way how `mkTMBStruc ` puts together the structure of the model. Would you have any advice on how I need to order my newdatabase to make sure that when `mkTMBStruc` is called I can get the same structure as the model I am inputting in `predict`?
I really hope this is clear and that someone can help me out. I am quite stuck now...

**Comment by mebrooks** [comment]
@MelanieDou, did you try @koenvanbenthem 's [solution](https://github.com/glmmTMB/glmmTMB/issues/383#issuecomment-418379129) of moving the columns instead of changing the names? Or did your example do that on purpose to add new levels to the RE terms? 

As for using predict from betareg with estimates from glmmTMB, that seems risky and difficult.

**Comment by MelanieDou** [comment]
I did that on purpose to show what kind of errors I was getting with my data. I wouldn't mind having to shuffle the columns around to avoid the error messages, but I am lacking the understanding of what I have to look for when shifting them around... Do you have an idea?

**Comment by kaskr** [comment]
Sounds like a problem in our formula machinery. We have the exact same formula and yet the formula interface thinks these are different models:

```
> form.prov.mixed_test
fraction ~ fixedeffect1 + (1 | randomeffect2/randomeffect1) + 
    (1 | randomeffect5) + (1 | randomeffect4/randomeffect3)
> newdatat$fraction <- rep(.5,nrow(newdatat))
> struct1 <- glmmTMB(form.prov.mixed_test, database_test, doFit=FALSE)
> struct2 <- glmmTMB(form.prov.mixed_test, newdatat, doFit=FALSE)
> glmmTMB:::assertIdenticalModels(struct1$data.tmb, struct2$data.tmb)
Error: identical(names(t1), names(t0)) is not TRUE
```

Looking closer it appears the terms have been reordered (is this related to #381 ?):

```
> names(struct1$data.tmb$terms)
[1] "1 | randomeffect3:randomeffect4" "1 | randomeffect1:randomeffect2"
[3] "1 | randomeffect4"               "1 | randomeffect5"              
[5] "1 | randomeffect2"              
> names(struct2$data.tmb$terms)
[1] "1 | randomeffect3:randomeffect4" "1 | randomeffect1:randomeffect2"
[3] "1 | randomeffect4"               "1 | randomeffect2"              
[5] "1 | randomeffect5"              
```

@bbolker and @mmaechler : How can we get a deterministic order of the terms ?

**Comment by kaskr** [comment]
@MelanieDou 
I seems that replacing `(1|A/B)` by `(1|A:B) + (1|B)` will make your example work ?

**Comment by MelanieDou** [comment]
@kaskr Thank you for the suggestion. It don't think it works for me.... However the example was more meant as an illustration. With my real data I am facing the issue even though there are no nested random effects.

**Comment by kaskr** [comment]
@MelanieDou 
Do you think you could post an example that has the issue without using nested random effects ?
If your example is very long it would probably be sufficient to see the `formula` along with the output of `names(struct1$data.tmb$terms)` and `names(struct2$data.tmb$terms)`.

**Comment by MelanieDou** [comment]
My code is quite long and I cannot share the data like that, so if the following is sufficient to give a better idea, I would be glad: 
```
> r.test <- eval(models.rnd[[1]][[1]])
> r.test$call$formula
fraction ~ (1 | Migrant_Name) + (1 | PolymerCAS.DisplayName) + 
    (1 | Food.NewName) + (1 | CitationID) + (1 | AnalMethod)
> newdatat <- database[database$rand.vec==1,]
> struct1 <- glmmTMB(r.test$call$formula, databases_rnd1, doFit=FALSE)
> names(struct1$data.tmb$terms)
[1] "1 | CitationID"             "1 | Food.NewName"           "1 | Migrant_Name"           "1 | PolymerCAS.DisplayName" "1 | AnalMethod"            
> struct2 <- glmmTMB(r.test$call$formula, newdatat, doFit=FALSE)
> names(struct2$data.tmb$terms)
[1] "1 | Food.NewName"           "1 | Migrant_Name"           "1 | CitationID"             "1 | PolymerCAS.DisplayName" "1 | AnalMethod"            
> glmmTMB:::assertIdenticalModels(struct1$data.tmb, struct2$data.tmb)
Error in checkTerms(data.tmb1$terms, data.tmb0$terms) : 
  identical(names(t1), names(t0)) is not TRUE
```
If not, please tell me I will come up with another example.
Thank you very much for your help!

**Comment by kaskr** [comment]
Thanks, this really does look bad.

**Comment by mebrooks** [comment]
Hi @MelanieDou, the new version of glmmTMB on CRAN has the bug fixed that was affecting the order or random effects. Does it fix your problem?

**Comment by MelanieDou** [comment]
Hi @mebrooks, I have been following the #384 and implemented the solution there which indeed fixed my problem yes. Thank you
