### ISSUE TITLE
order of reTrms from lme4:::mkReTrms

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#384]
This issue keeps popping up in other issues (#329, #381, #383) so @kaskr and I decided it would be easiest to get feedback and discuss it if we summarize the problem in its own issue. 

The problem is that the order of the random effects coming from `lme4:::mkReTrms` is inconsistent.  Here is an example
```
library(glmmTMB)
data(sleepstudy, package="lme4")
sleepstudy2=subset(sleepstudy, Subject==308)

form=Reaction ~ Days + (1| Subject)+(1|Days)

fm1 = glmmTMB(form, sleepstudy, doFit = FALSE)
fm2 = glmmTMB(form, sleepstudy2, doFit = FALSE)

reTrms1 = lme4:::mkReTrms(lme4:::findbars(lme4:::RHSForm(form)), fm1$fr)
reTrms2 = lme4:::mkReTrms(lme4:::findbars(lme4:::RHSForm(form)), fm2$fr)

names(reTrms1$Ztlist)
names(reTrms2$Ztlist)
```

Is there a way to make it consistent or to predict its behavior?

**Comment by mebrooks** [comment]
A comment in lme4's `utilities.R` [says](https://github.com/lme4/lme4/blob/40f86be5bec9169c8686ddf0ca6d42f47cf2765c/R/utilities.R#L129) `## order terms stably by decreasing number of levels in the factor`.

**Comment by kaskr** [comment]
Looks like the reordering is hard coded. It's tempting to copy `mkReTrms` and adapt it for our needs.

**Comment by bbolker** [comment]
What about asking the `lme4` maintainers (ahem) to add an optional `reorder` argument defaulting to `TRUE`?

While we're at it we might want to do something about ordering *within* terms, to address https://github.com/lme4/lme4/issues/449 ...

The only downside that I can see to this is that it would add a dependency to a not-yet-released version of `lme4`, which could hold up future `glmmTMB` releases - although I guess if you were really desperate you could *temporarily* add a local copy of `mkReTrms` and revert it after the updated `lme4` version was released ...

**Comment by mmaechler** [comment]
Yes, "copy and modify" is *not* a good idea (DRY: Don't Repeat Yourself!) and yes, the way `lme4` does it *is* deterministic, very much on purpose and Doug Bates has always emphasized why it was a very good idea: The sparse Cholesky algorithms typically are more efficient and/or lead to considerably more sparse results that way.   But indeed a new optional argument `reorder = TRUE` seems like a very good idea by @bbolker  to me!

**Comment by MelanieDou** [comment]
@bbolker I would be desperate for such a quick and temporary fix...

**Comment by kaskr** [comment]
@bbolker Good to see this has been fixed in lme4. Just tried it out in glmmTMB and it seems to work.

Result from `make test`:

```
OK:       266
Failed:   3
Warnings: 4
Skipped:  0
```

The failed ones are some tests that relied on the parameter order.


@MelanieDou does it solve your problem:
```
devtools::install_github("lme4/lme4",dependencies=TRUE)
devtools::install_github("glmmTMB/glmmTMB/glmmTMB", ref="fix_covstruct_order2")
```

**Comment by kaskr** [comment]
@Kreitzberg 
Should be in the master branch now (I think). Try:
```
devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
```

**Comment by Kreitzberg** [comment]
@kaskr thanks for the quick reply, I tried the master branch and I was still getting the error when trying to run the predict function. Hopefully its just not in the master branch!

**Comment by kaskr** [comment]
@Kreitzberg Yes it is in the master branch.
Which example doesn't work?

**Comment by Kreitzberg** [comment]
Oh bummer, I wish it were that simple. So I didn't run the example data above but I ran a GLMM (link=logit) and I am trying to use it to predict the same dichotomous outcome with some other data but I am getting the error

`Error in checkTerms(data.tmb1$terms, data.tmb0$terms) : 
  identical(names(t1), names(t0)) is not TRUE`

`R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] bindrcpp_0.2.2  glmmTMB_0.2.3   caret_6.0-81   
[4] lattice_0.20-35 ggplot2_3.1.0   dplyr_0.7.8    

loaded via a namespace (and not attached):
 [1] httr_1.4.0         pkgload_1.0.2      splines_3.5.1     
 [4] foreach_1.4.4      prodlim_2018.04.18 assertthat_0.2.0  
 [7] stats4_3.5.1       remotes_2.0.2      yaml_2.2.0        
[10] sessioninfo_1.1.1  ipred_0.9-8        backports_1.1.3   
[13] pillar_1.3.1       glue_1.3.0         digest_0.6.18     
[16] minqa_1.2.4        colorspace_1.3-2   recipes_0.1.4     
[19] Matrix_1.2-14      plyr_1.8.4         timeDate_3043.102 
[22] pkgconfig_2.0.2    devtools_2.0.1     purrr_0.2.5       
[25] scales_1.0.0       processx_3.2.1     gower_0.1.2       
[28] lava_1.6.4         **lme4_1.1-19.9000**   tibble_1.4.2      
[31] generics_0.0.2     usethis_1.4.0      withr_2.1.2       
[34] **TMB_1.7.15**         nnet_7.3-12        lazyeval_0.2.1    
[37] cli_1.0.1          survival_2.42-3    magrittr_1.5      
[40] crayon_1.3.4       memoise_1.1.0      ps_1.2.1          
[43] fs_1.2.6           nlme_3.1-137       MASS_7.3-50       
[46] class_7.3-14       pkgbuild_1.0.2     tools_3.5.1       
[49] data.table_1.11.8  prettyunits_1.0.2  stringr_1.3.1     
[52] munsell_0.5.0      callr_3.1.0        compiler_3.5.1    
[55] forge_0.1.0        rlang_0.3.0.1      nloptr_1.2.1      
[58] grid_3.5.1         iterators_1.0.10   rstudioapi_0.8    
[61] base64enc_0.1-3    testthat_2.0.1     gtable_0.2.0      
[64] ModelMetrics_1.2.2 codetools_0.2-15   curl_3.2          
[67] DBI_1.0.0          reshape2_1.4.3     R6_2.3.0          
[70] lubridate_1.7.4    knitr_1.21         rprojroot_1.3-2   
[73] bindr_0.1.1        desc_1.2.0         stringi_1.2.4     
[76] Rcpp_1.0.0         rpart_4.1-13       tidyselect_0.2.5  
[79] xfun_0.4 `

**Comment by Kreitzberg** [comment]
Thank you @bbolker I'll give  it a try with a clean R session. Just to be sure, it doesn't matter the context that the model was run for purposes of using it to predict, correct? For example, if I used an older version of glmmTMB to create the model then try to predict with a newer version?

**Comment by bbolker** [comment]
I'm not actually sure that's true.  I can imagine that a model created before we fixed this issue could retain the problem. If such a model fails in prediction it *might* be possible to hack it to make it work (e.g. if the fitting procedure was very cumbersome), but it really require mucking around with the guts of the object ...

**Comment by Kreitzberg** [comment]
Oh interesting, okay well I definitely fit the model using the older version of glmmTMB but I just fit a new model so I'll see if that works now. The fitting procedure was pretty cumbersome (the dataset is about 1.7m rows) but I don't mind just refitting it if need be. 

I meant to ask you @bbolker for large datasets and convergence issues does throwing memory at the model help with convergence issues or does it merely increase the speed by which the model will converge. For example, I was trying to run a glmm using sparklyr's spark_apply() + glmmTMB, still haven't been able to make it work correctly but I had a hunch that it wouldn't actually help with convergence just speed up the time it took to reach convergence if in fact convergence was possible.

**Comment by Kreitzberg** [comment]
Another thing when I load the saved environment that includes the model I am getting this warning.

`Warning: namespace ‘TMB’ is not available and has been replaced
by .GlobalEnv when processing object ‘Model4’
Warning: namespace ‘glmmTMB’ is not available and has been replaced
by .GlobalEnv when processing object ‘Model4’`

Not sure if this could be the issue but I thought I would share to see if yall have any advice.

**Comment by bbolker** [comment]
I'm not actually sure that's true.  I can imagine that a model created before we fixed this issue could retain the problem. If such a model fails in prediction it *might* be possible to hack it to make it work (e.g. if the fitting procedure was very cumbersome), but it really require mucking around with the guts of the object ...

**Comment by bbolker** [comment]
You can probably get rid of that warning by using `library("TMB"); library("glmmTMB")` before loading the environment/model.

**Comment by bbolker** [comment]
>  I meant to ask you @bbolker 

@kaskr is more qualified to answer difficult technical questions, FWIW (although I can answer this one)

> for large datasets and convergence issues does throwing memory at the model help with convergence issues or does it merely increase the speed by which the model will converge. 

That's right. Memory might not even help speed at all; if your problem *is* memory-bound, it will be **very** slow (lots of swapping/paging), otherwise more memory won't speed things up. If your problem is CPU-bound (more likely), then more memory won't help speed.  In any case I wouldn't expect convergence to be affected by anything but the data set and model (and platform details in very unstable/edge cases).

**Comment by Kreitzberg** [comment]
Thanks so much @bbolker and @kaskr I am running the model over again after making sure I have the most up-to-date version of glmmTMB. I'll know soon.

**Comment by Kreitzberg** [comment]
> Just to be sure, it doesn't matter the context that the model was run for purposes of using it to predict, correct? For example, if I used an older version of glmmTMB to create the model then try to predict with a newer version?

This was in fact not true, the predict function was not working with models that were trained on the older version of glmmTMB even though I was using the master branch install. Once I fit the model with the master branch install the predict function worked.

Thanks for your help! @bbolker @kaskr
