### ISSUE TITLE
Loading old fit with new version

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#651]
Some of the glmmTMB tests assume that fitted objects saved with old
versions of the package remain valid 'forever' even when TMB and/or
glmmTMB are updated - e.g. `fm2` [here](https://github.com/glmmTMB/glmmTMB/blob/2b14a42bd55cd0cfeebad1f4eb7a3b2313e5d359/glmmTMB/tests/testthat/test-methods.R#L13).
This is currently too much to ask for. Objects saved with a given
version are only guarantied to work when loaded with the same version.

I noticed this problem while testing a future version of TMB:

```r
devtools::install_github("kaskr/adcomp/TMB", ref="TMB_experimental")
devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
```

followed by `make test` from glmmTMB main folder.
I got a bunch of these:

> test-methods.R:73: error: Predict
> gradient in optim evaluated to length 1 not 6
> Backtrace:
>  1. stats::predict(fm2, se.fit = TRUE) tests/testthat/test-methods.R:73:4
>  2. glmmTMB::predict.glmmTMB(fm2, se.fit = TRUE)
>  4. base::with.default(object, optimHess(oldPar, obj$fn, obj$gr))
>  5. [ base::eval(...) ] with 1 more call
>  7. stats::optimHess(oldPar, obj$fn, obj$gr)

**Comment by bbolker** [comment]
Perhaps I'm missing the point, but I had assumed that we would rebuild the examples every time we needed to. There's a Makefile and a make rule for `models.rda` in `inst/test_data`; does that address the problem?

I'm not sure what kind of machinery/rules we have for testing/ensuring that the versions of `glmmTMB` and `TMB` are properly synchronized, or whether we can add a mechanism for knowing when `models.rda` needs to be re-built ...

**Comment by kaskr** [comment]
Thanks @bbolker 
I tried to

```
rm models.rds
make
```

before re-installing glmmTMB.

Now `make test` almost works - there's only one error left:

> test-sparseX.R:23: error: back-compatibility
> Incorrect number of arguments (3), expecting 4 for 'MakeDoubleFunObject'
> Backtrace:
>  1. testthat::expect_is(VarCorr(x), "VarCorr.glmmTMB") tests/testthat/test-sparseX.R:23:4
>  5. glmmTMB::VarCorr.glmmTMB(x)
>  6. x$obj$env$report(x$fit$parfull) R/VarCorr.R:173:4

This last error is due to `test_data/oldfit.rds` which must also be updated.

I wonder what is the reason for saving all these fits rather than running from scratch each time? Speed? (It really doesn't take a long time to generate them...)

**Comment by bbolker** [comment]
The `oldfit` example is  a bit of a problem, as it was developed to make sure that the code to allow old fits (which had different `terms` structure: see  [here](https://github.com/glmmTMB/glmmTMB/commit/388dda56be487bc945f77e2c811f234c3328e6ce )) could still be used. Do we have any official policy about the circumstances under which glmmTMB can/cannot be expected to be backward-compatible with stored model fits from previous version?  We might want to think about this ...

It's true that the fits only take about 5 seconds on my machine at this point, but these fitted objects could (should) get re-used in many different contexts. Hopefully other long-running objects could also be included in this set. I spent a lot of time and effort recently trying to get `lme4` checks under 10 minutes on Windows (CRAN's Windows machine runs tests about 2x as slow as on my machine, and every test needed to be repeated on ix86 and x86_64 platforms;  in fact [the current CRAN checks](https://cran.r-project.org/web/checks/check_results_glmmTMB.html) show that the check process is already at 672 seconds, over the recommended 10-min maximum, so we probably need to streamline the tests further before resubmitting (we can use a lot of `testthat::skip_on_cran()`)

**Comment by bbolker** [comment]
Should we just comment out the `oldfit` test? (I hate it when maintaining the tests becomes more work than maintaining the underlying package ...)

**Comment by kaskr** [comment]
@bbolker Yes, I think so until loading and saving objects between different versions of TMB becomes a supported feature.

**Comment by bbolker** [comment]
OK, I took the liberty of pushing this directly to the master branch 2162e8fc38

**Comment by mebrooks** [comment]
I don't think the problem was just with the old fits because I still get an error similar to kaskr above. 

I did `devtools::install_github("kaskr/adcomp/TMB", ref="TMB_experimental")` and then checked out and pulled the master branch of glmmTMB. Then ran `make install` and got an error on a vignette.

```
Error: processing vignette 'model_evaluation.Rnw' failed with diagnostics:
Incorrect number of arguments (3), expecting 4 for 'MakeDoubleFunObject'
--- failed re-building ‘model_evaluation.Rnw’

SUMMARY: processing the following file failed:
  ‘model_evaluation.Rnw’

Error: Vignette re-building failed.
Execution halted
make: *** [glmmTMB_1.0.2.9000.tar.gz] Error 1
```
So I tried running that line by line and the first error occurs the first time a model gets evaluated (chunk 4).

```
> data("cbpp",package="lme4")
> cbpp_b1 <- glmmTMB(incidence/size~period+(1|herd),
+                    weights=size,family=binomial,
+                    data=cbpp)
Error in .Call("getParameterOrder", data, parameters, new.env(), NULL,  : 
  Incorrect number of arguments (4), expecting 3 for 'getParameterOrder'
> traceback()
7: MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg, 
       profile = NULL, silent = !verbose, DLL = "glmmTMB")
6: eval(substitute(expr), data, enclos = parent.frame())
5: eval(substitute(expr), data, enclos = parent.frame())
4: with.default(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, 
       random = randomArg, profile = NULL, silent = !verbose, DLL = "glmmTMB"))
3: with(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, 
       random = randomArg, profile = NULL, silent = !verbose, DLL = "glmmTMB"))
2: fitTMB(TMBStruc)
1: glmmTMB(incidence/size ~ period + (1 | herd), weights = size, 
       family = binomial, data = cbpp)
```

**Comment by kaskr** [comment]
@mebrooks  Thanks for looking into this issue!

I'm guessing the error might be caused by `cache=TRUE` which implicitly saves/loads (?).

```r
<<fit_model3,cache=TRUE>>=
data("cbpp",package="lme4")
cbpp_b1 <- glmmTMB(incidence/size~period+(1|herd),
                   weights=size,family=binomial,
                   data=cbpp)
## simulated three-term Beta example
set.seed(1001)
dd <- data.frame(z=rbeta(1000,shape1=2,shape2=3),
                 a=rnorm(1000),b=rnorm(1000),c=rnorm(1000))
simex_b1 <- glmmTMB(z~a*b*c,family=beta_family,data=dd)
@
```

**Comment by mebrooks** [comment]
With this installation, I just opened up a new R console and got the same error, so my glmmTMB is broken.

Let me know if there's anything I can do to help.
```
> library(glmmTMB)
> data("cbpp",package="lme4")
> cbpp_b1 <- glmmTMB(incidence/size~period+(1|herd),
+                    weights=size,family=binomial,
+                    data=cbpp)
Error in .Call("getParameterOrder", data, parameters, new.env(), NULL,  : 
  Incorrect number of arguments (4), expecting 3 for 'getParameterOrder'
> traceback()
7: MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg, 
       profile = NULL, silent = !verbose, DLL = "glmmTMB")
6: eval(substitute(expr), data, enclos = parent.frame())
5: eval(substitute(expr), data, enclos = parent.frame())
4: with.default(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, 
       random = randomArg, profile = NULL, silent = !verbose, DLL = "glmmTMB"))
3: with(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, 
       random = randomArg, profile = NULL, silent = !verbose, DLL = "glmmTMB"))
2: fitTMB(TMBStruc)
1: glmmTMB(incidence/size ~ period + (1 | herd), weights = size, 
       family = binomial, data = cbpp)

```

**Comment by kaskr** [comment]
@mebrooks OK, that makes sense. The error tells me that you have the new TMB but forgot to recompile glmmTMB.

**Comment by mebrooks** [comment]
Yep, that was it. I fixed the error by doing 
```devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
```
but before that, I tried touching `glmmTMB.cpp` then `make install`. It recompiled glmmTMB, but still gave me the same set of errors. I'm not sure why.

**Comment by kaskr** [comment]
Unfortunately not solved yet. `make test` gives a large number of these:

✖ |  26 7 18 1 | basic methods [4.1 s]                                                                                                                                                                      
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-methods.R:19:5): Fitted and residuals
Error: Incorrect number of arguments (3), expecting 4 for 'MakeDoubleFunObject'
Backtrace:
  1. testthat::expect_equal(length(fitted(fm2)), nrow(sleepstudy)) test-methods.R:19:4
  5. glmmTMB::fitted.glmmTMB(fm2)
  7. glmmTMB::predict.glmmTMB(object, type = "response", fast = TRUE)
  8. newObj$report(lp) /zhome/8a/0/39821/SLETMIG/glmmTMB/glmmTMB/R/predict.R:374:4
  9. TMB:::f(par, order = 0, type = "double")
 10. TMB:::retape(set.defaults = FALSE)

**Comment by mebrooks** [comment]
This seems to be fixed for now with `skip until TMB fits are back-compatible`. Should we close it and reopen later? Or keep it open?

**Comment by bbolker** [comment]
I guess we're going to give up on testing backward compatibility, which makes me sad but I don't really see any way around it. We should probably comment out those tests so they don't show up as "skipped" when running `devtools::test()`, unless we want to reminder/frustrate ourselves in the future ...

**Comment by bbolker** [comment]
Re-opening.

We have two clashing priorities: (1) Set things up so tests and vignettes run fast enough, primarily on CRAN (600-second maximum check time on Windows, which in really is almost half that because tests and examples get run twice, on both `i386` and `x64` architectures); (2) ensure that future releases of TMB won't break tests of current glmmTMB releases (so that we don't have to coordinate releases).

One of the main things I did to get the tests running fast enough was to restore the load-saved-objects machinery in [tests/testthat/setup_makeex.R](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/tests/testthat/setup_makeex.R).

Other than almost completely skipping tests, it's tough to know how we can make this work fast enough without storing fits ...  unfortunately, the `testthat` framework doesn't (AFAICS) make it easy to break test timing down by individual test/component (so that we could have an *informed* opinion about , although we could certainly build our own framework to figure that out.  (Ideally I would want annotated output from a complete run that gave a detailed timing breakdown of every step.)  I guess we need to open and/or reopen an issue?

[this page](https://github.com/bradleyboehmke/unit-testing-r) describes general unit testing strategies, including both `testthat` and `tinytest`.  It says `tinytest` is faster than `testthat` ... I wonder if that would help us? (It would require a big chunk of reorganization, although that would be more tedious than difficult.)

As usual, I'm also tempted to ask on `r-package-devel@r-project.org`, although I don't know if we would get anything useful. 

One small, potentially useful point of information is that `testthat::skip_on_cran()` *only* works to short-circuit code *within* a `test_that()` block: I don't know if there's the analog of a `break` statement that will stop testing at the level of a test *file* without triggering an error (e.g., we presumably can't use `if (on_cran()) stop()`. We can always use an `if () { ...}` clause, but that's harder to read than a "bail out now"/`break` statement.

**Comment by kaskr** [comment]
@bbolker  As part of the next glmmTMB release (https://github.com/glmmTMB/glmmTMB/issues/751) I very much insist on getting  #651 fixed.

If loading old fits really is necessary for the glmmTMB tests it has to be part of the design. To bring an old fit up to date one can use something like:

```r
up2date <- function(oldfit) {
  if (TMB:::isNullPointer(oldfit$obj$env$ADFun$ptr)) {
    obj <- oldfit$obj
    oldfit$obj <- TMB::MakeADFun(obj$env$data,
                                 obj$env$parameters, 
                                 map = obj$env$map,
                                 random = obj$env$random, 
                                 silent = obj$env$silent,
                                 DLL = "glmmTMB")
    oldfit$obj$env$last.par.best <- obj$env$last.par.best
  }
  oldfit
}
```

For instance one can do

```r
system.time(m <- readRDS("glmmTMB/inst/test_data/oldfit.rds"))
system.time(m <- up2date(m)) ## Fast compared to loading
```

TODO:

- Add `m <- up2date(m)` everywhere a loaded object is used !
- **or** Is there a way to do this automatically?

**Comment by bbolker** [comment]
TBH I don't remember the *actual* status of the machinery; I know that the testing machinery can be made to work [either with or without stored fits](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/tests/testthat/setup_makeex.R). What I don't remember is whether I used enough "skip on CRAN" stuff in the last submitted release that we can run everything in Windows fast enough even if we don't have the objects stored (there is a whole series of commits where I tried to skip enough stuff, going back to win-builder every time to see if I had done enough, e.g. [a](https://github.com/glmmTMB/glmmTMB/commit/620777579e892239eb96a6994b378c985dfde461), [b](https://github.com/glmmTMB/glmmTMB/commit/0dfa5dc247664321df986b65643f2ce3edaa942a), [c](https://github.com/glmmTMB/glmmTMB/commit/ee6bef52fe193d5d45dfa2e2b5240d2f35f172ef) ...) 

On looking at that bit of the commit history, I don't think so. In other words, I think we should add your `up2date()` function to [testthat/setup_makeex.R](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/tests/testthat/setup_makeex.R). My guess is that's the only place where we actually use loaded objects, although of course be good it would be best to have a testing framework so we can make sure ...

**Comment by bbolker** [comment]
First effort [here](19749cbb4); there are also some messages about tests that are skipped "until TMB fits are back-compatible" - these are harmless but we should see if we can go back and un-skip them now ...

**Comment by bbolker** [comment]
Not a big deal, but is there a reason we can't simplify the `MakeADFun` call to

```r
oldfit$obj <- with(obj$env,
     TMB::MakeADFun(data, parameters, map = map, random = random, silent = silent,
                                   DLL = "glmmTMB"))
```

?

**Comment by kaskr** [comment]
@bbolker Thanks for looking into this.

It tried your new branch https://github.com/glmmTMB/glmmTMB/tree/update_stored with TMB from https://github.com/kaskr/adcomp/tree/TMB_experimental. Then running `make test`. It gets me through some tests but there are still a lot of glmmTMB objects that need to be run through `up2date` - all output of `grep load *.R` should be considered. For example, despite its name, "lme-tst-fits.rda" has glmmTMB fits!

It may be that `up2date()` will have to be in a more central place of glmmTMB so it can be used in vignettes as well?

Here some examples of errors I'm getting:

```
Error (test-methods.R:18:5): Fitted and residuals
Error: Incorrect number of arguments (3), expecting 4 for 'MakeDoubleFunObject'
Backtrace:
  1. testthat::expect_equal(length(fitted(fm2)), nrow(sleepstudy)) test-methods.R:18:4
  5. glmmTMB::fitted.glmmTMB(fm2)
  7. glmmTMB::predict.glmmTMB(object, type = "response", fast = TRUE)
  8. newObj$report(lp) /zhome/8a/0/39821/glmmTMB/glmmTMB/R/predict.R:386:4
  9. TMB:::f(par, order = 0, type = "double")
 10. TMB:::retape(set.defaults = FALSE

Warning (test-methods.R:279:5): profile
NA/NaN function evaluation
Backtrace:
  1. stats::profile(fm1, parm = "theta_", npts = 4) test-methods.R:279:4
  2. glmmTMB::profile.glmmTMB(fm1, parm = "theta_", npts = 4)
  3. base::Map(FUN, parm, sds) /zhome/8a/0/39821/glmmTMB/glmmTMB/R/profile.R:141:8
  4. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
  6. TMB::tmbprofile(...) /zhome/8a/0/39821/glmmTMB/glmmTMB/R/profile.R:115:12
  7. TMB:::evalAlongLine(h)
  8. TMB:::f(x)
 14. TMB:::f.original(x)
 15. stats::nlminb(start, newfn, newgr, control = control)
```

**Comment by bbolker** [comment]
Working on it ...

**Comment by bbolker** [comment]
- note that glmmTMB must be reinstalled *from source* after installing the TMB experimental branch (I used `remotes::install_github("kaskr/adcomp/TMB@TMB_experimental")`)
- I don't think "lme-tst-fits.rda" does have glmmTMB fits in it??
```r
L <- load(system.file("testdata", "lme-tst-fits.rda",
                          package="lme4", mustWork=TRUE))
sapply(L, function(x) class(get(x)))
```
- we need to do something about `TMB:::isNullPointer` before submitting to CRAN. Can this be exported from TMB ... ?
- I'd like to make sure that we re-consider https://github.com/glmmTMB/glmmTMB/pull/667/ in light of these TMB compatibility issues ... ??
- `make test` works now, trying `make check` ...

**Comment by kaskr** [comment]
I must have been looking a the wrong file...

- The following replacement function can be used without exports:

```r
isNullPointer <- function(x) { attributes(x) <- NULL; identical(x, new("externalptr")) }
```

**Comment by bbolker** [comment]
`make check` doesn't work. That is, there's something weird about environments (see `gt_load()`, which tries to load a file, update the glmmTMB objects, and assign the results in the parent frame) such that the updating works properly with `devtools::test()` but *fails* with `devtools::check()`. Arrgh.

**Comment by kaskr** [comment]
FWIW a different approach is sketched here that might be simpler to maintain (no need for `gt_load` - saving/loading 'just works'):
https://github.com/glmmTMB/glmmTMB/tree/update_stored2
(I know it's not good practice to modify R-objects but seems safe in this case?)

**Comment by bbolker** [comment]
Safe but ugly.  I will fight with `gt_load()` a little bit more, seems more principled?

**Comment by bbolker** [comment]
Closed  (tests use `up2date` by brute force where necessary - cleaner than updating all the time within the package itself). https://github.com/glmmTMB/glmmTMB/commit/c689f5f19027efb7fd67258c3ecd5015961c285d
